version: '3.6'
services:
  visitor_counter_app1:
    build: visitor_counter_app/.
    image: visitor_counter_app:v1.0.0
    ports:
    - "8001:8001"
    environment:
      CONTAINER_NAME: boom
      PORT: 8001
      REDIS_HOST: 'redis'
    networks:
      - my_network
    depends_on:
      - redis
  visitor_counter_app2:
    build: visitor_counter_app/.
    image: visitor_counter_app:v1.0.0
    ports:
    - "8002:8002"
    environment:
      CONTAINER_NAME: bahhh
      PORT: 8002
      REDIS_HOST: 'redis'
    networks:
      - my_network
    depends_on:
      - redis
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - "./nginx/default.conf:/etc/nginx/conf.d/default.conf"
    networks:
      - my_network
    depends_on:
      - visitor_counter_app1
      - visitor_counter_app2
  redis:
    image: redis
    networks:
      - my_network
networks:
  my_network: